import type { Vehicle, Seller, ImageInfo } from './types';
import { PlaceHolderImages } from './placeholder-images';

const sellers: Record<string, Seller> = {
  seller1: { id: 'seller1', name: 'Juan Perez', isVerified: true, phone: '+584141234567' },
  seller2: { id: 'seller2', name: 'Maria Rodriguez', isVerified: false, phone: '+584129876543' },
  seller3: { id: 'seller3', name: 'Carlos Gomez', isVerified: true, phone: '+584241122334' },
};

const getImage = (id: string): ImageInfo => {
    const img = PlaceHolderImages.find(p => p.id === id);
    if (!img) return { url: 'https://picsum.photos/seed/default/800/600', alt: 'Placeholder', hint: 'image' };
    return { url: img.imageUrl, alt: img.description, hint: img.imageHint };
}

export const vehicles: Vehicle[] = [
  {
    id: '1',
    make: 'Toyota',
    model: 'Corolla',
    year: 2021,
    priceUSD: 22000,
    mileage: 15000,
    bodyType: 'Sedán',
    transmission: 'Automática',
    engine: '1.8L 4-Cylinder',
    exteriorColor: 'Blanco',
    interiorColor: 'Negro',
    doorCount: '4',
    ownerCount: 1,
    tireLife: 90,
    hasAC: true,
    hasSoundSystem: true,
    hadMajorCrash: false,
    isOperational: true,
    isSignatory: true,
    acceptsTradeIn: false,
    description: 'Impecable Toyota Corolla, como nuevo. Único dueño, todos los servicios realizados en el concesionario. Un auto confiable y económico para la ciudad.',
    images: [ getImage('corolla-main'), getImage('corolla-interior'), getImage('corolla-side') ],
    seller: sellers.seller1,
    location: { city: 'Caracas', state: 'Distrito Capital', lat: 10.4806, lon: -66.9036 },
  },
  {
    id: '2',
    make: 'Toyota',
    model: 'Fortuner',
    year: 2022,
    priceUSD: 55000,
    mileage: 5000,
    bodyType: 'SUV',
    transmission: 'Automática',
    engine: '4.0L V6',
    exteriorColor: 'Plata',
    interiorColor: 'Marrón',
    is4x4: true,
    ownerCount: 1,
    tireLife: 95,
    hasAC: true,
    hasSoundSystem: true,
    hadMajorCrash: false,
    isOperational: true,
    isSignatory: true,
    acceptsTradeIn: true,
    tradeInForLowerValue: true,
    description: 'Potente y lujosa Toyota Fortuner 4x4. Perfecta para la familia y la aventura. Muy poco kilometraje, prácticamente nueva. Lista para cualquier terreno.',
    images: [ getImage('fortuner-main'), getImage('fortuner-interior') ],
    seller: sellers.seller2,
    location: { city: 'Maracaibo', state: 'Zulia', lat: 10.6421, lon: -71.6125 },
  },
  {
    id: '3',
    make: 'Toyota',
    model: 'Land Cruiser',
    year: 2018,
    priceUSD: 45000,
    mileage: 80000,
    bodyType: 'Camioneta',
    transmission: 'Sincrónica',
    engine: '4.5L V8 Diesel',
    exteriorColor: 'Beige Arena',
    interiorColor: 'Gris',
    is4x4: true,
    ownerCount: 2,
    tireLife: 70,
    hasAC: true,
    hasSoundSystem: false,
    hadMajorCrash: false,
    isOperational: true,
    isSignatory: true,
    acceptsTradeIn: true,
    tradeInDetails: 'Solo camionetas más nuevas',
    tradeInForHigherValue: true,
    description: 'El legendario "Machito". Una bestia preparada para el off-road más exigente. Muchos extras incluidos. Un verdadero caballo de batalla que nunca se rinde.',
    images: [ getImage('machito-main') ],
    seller: sellers.seller3,
    location: { city: 'Valencia', state: 'Carabobo', lat: 10.162, lon: -68.0076 },
  },
  {
    id: '4',
    make: 'Jeep',
    model: 'Grand Cherokee',
    year: 2020,
    priceUSD: 48000,
    mileage: 35000,
    bodyType: 'SUV',
    transmission: 'Automática',
    engine: '3.6L V6',
    exteriorColor: 'Negro',
    interiorColor: 'Negro',
    is4x4: true,
    ownerCount: 1,
    tireLife: 80,
    hasAC: true,
    hasSoundSystem: true,
    hadMajorCrash: false,
    isOperational: true,
    isSignatory: true,
    acceptsTradeIn: false,
    description: 'Elegante y capaz Jeep Grand Cherokee Limited. Una combinación perfecta de lujo y capacidad todoterreno. Excelente estado.',
    images: [ getImage('cherokee-main') ],
    seller: sellers.seller1,
    location: { city: 'Caracas', state: 'Distrito Capital', lat: 10.5000, lon: -66.9167 },
  },
  {
    id: '5',
    make: 'Hyundai',
    model: 'Elantra',
    year: 2019,
    priceUSD: 16000,
    mileage: 55000,
    bodyType: 'Sedán',
    transmission: 'Automática',
    engine: '2.0L 4-Cylinder',
    exteriorColor: 'Azul',
    interiorColor: 'Beige',
    doorCount: '4',
    ownerCount: 2,
    tireLife: 60,
    hasAC: true,
    hasSoundSystem: true,
    hadMajorCrash: true,
    isOperational: true,
    isSignatory: false,
    acceptsTradeIn: false,
    description: 'Moderno y eficiente Hyundai Elantra. Ideal para el uso diario. Espacioso y cómodo, con bajo consumo de combustible.',
    images: [ getImage('elantra-main') ],
    seller: sellers.seller2,
    location: { city: 'Barquisimeto', state: 'Lara', lat: 10.0678, lon: -69.3572 },
  },
  {
    id: '6',
    make: 'Kawasaki',
    model: 'Ninja 400',
    year: 2023,
    priceUSD: 8000,
    mileage: 1000,
    bodyType: 'Moto',
    transmission: 'Sincrónica',
    engine: '399cc',
    exteriorColor: 'Verde',
    interiorColor: 'Negro',
    ownerCount: 1,
    tireLife: 99,
    hasAC: false,
    hasSoundSystem: false,
    hadMajorCrash: false,
    isOperational: true,
    isSignatory: true,
    acceptsTradeIn: false,
    description: 'Motocicleta deportiva casi nueva, perfecta para la ciudad y carretera.',
    images: [ getImage('motorcycle-new') ],
    seller: sellers.seller1,
    location: { city: 'Caracas', state: 'Distrito Capital', lat: 10.4806, lon: -66.9036 },
  },
];
