import type { Vehicle, Seller, ImageInfo } from './types';
import { PlaceHolderImages } from './placeholder-images';

const sellers: Record<string, Seller> = {
  seller1: { id: 'seller1', name: 'Juan Perez', isVerified: true, phone: '+584141234567' },
  seller2: { id: 'seller2', name: 'Maria Rodriguez', isVerified: false, phone: '+584129876543' },
  seller3: { id: 'seller3', name: 'Carlos Gomez', isVerified: true, phone: '+584241122334' },
};

const getImage = (id: string): ImageInfo => {
    const img = PlaceHolderImages.find(p => p.id === id);
    if (!img) return { url: 'https://picsum.photos/seed/default/800/600', alt: 'Placeholder', hint: 'image' };
    return { url: img.imageUrl, alt: img.description, hint: img.imageHint };
}

export const vehicles: Vehicle[] = [
  {
    id: '1',
    make: 'Toyota',
    model: 'Corolla',
    year: 2021,
    priceUSD: 22000,
    mileage: 15000,
    bodyType: 'Sedán',
    exteriorColor: 'White',
    interiorColor: 'Black',
    transmission: 'Automatic',
    engine: '1.8L 4-Cylinder',
    location: { city: 'Caracas', state: 'Distrito Capital', lat: 10.4806, lon: -66.9036 },
    features: ['Apple CarPlay', 'Android Auto', 'Monitor de Punto Ciego', 'Techo Corredizo'],
    description: 'Impecable Toyota Corolla, como nuevo. Único dueño, todos los servicios realizados en el concesionario. Un auto confiable y económico para la ciudad.',
    images: [
      getImage('corolla-main'),
      getImage('corolla-interior'),
      getImage('corolla-side'),
    ],
    seller: sellers.seller1,
  },
  {
    id: '2',
    make: 'Toyota',
    model: 'Fortuner',
    year: 2022,
    priceUSD: 55000,
    mileage: 5000,
    bodyType: 'SUV',
    exteriorColor: 'Silver',
    interiorColor: 'Brown',
    transmission: 'Automatic',
    engine: '4.0L V6',
    location: { city: 'Maracaibo', state: 'Zulia', lat: 10.6421, lon: -71.6125 },
    features: ['4x4', 'Asientos de Cuero', '7 Puestos', 'Cámara 360', 'Sensores de Estacionamiento'],
    description: 'Potente y lujosa Toyota Fortuner 4x4. Perfecta para la familia y la aventura. Muy poco kilometraje, prácticamente nueva. Lista para cualquier terreno.',
    images: [
      getImage('fortuner-main'),
      getImage('fortuner-interior'),
    ],
    seller: sellers.seller2,
  },
  {
    id: '3',
    make: 'Toyota',
    model: 'Land Cruiser',
    year: 2018,
    priceUSD: 45000,
    mileage: 80000,
    bodyType: 'Camioneta',
    exteriorColor: 'Beige',
    interiorColor: 'Gray',
    transmission: 'Manual',
    engine: '4.5L V8 Diesel',
    location: { city: 'Valencia', state: 'Carabobo', lat: 10.162, lon: -68.0076 },
    features: ['4x4', 'Snorkel', 'Winch', 'Portaequipajes de techo', 'Suspensión Mejorada'],
    description: 'El legendario "Machito". Una bestia preparada para el off-road más exigente. Muchos extras incluidos. Un verdadero caballo de batalla que nunca se rinde.',
    images: [
      getImage('machito-main'),
    ],
    seller: sellers.seller3,
  },
  {
    id: '4',
    make: 'Jeep',
    model: 'Grand Cherokee',
    year: 2020,
    priceUSD: 48000,
    mileage: 35000,
    bodyType: 'SUV',
    exteriorColor: 'Black',
    interiorColor: 'Black',
    transmission: 'Automatic',
    engine: '3.6L V6',
    location: { city: 'Caracas', state: 'Distrito Capital', lat: 10.5000, lon: -66.9167 },
    features: ['Versión Limited', 'Techo Corredizo', 'Asientos de Cuero', 'Pantalla Uconnect de 8.4 pulgadas'],
    description: 'Elegante y capaz Jeep Grand Cherokee Limited. Una combinación perfecta de lujo y capacidad todoterreno. Excelente estado.',
    images: [
      getImage('cherokee-main'),
    ],
    seller: sellers.seller1,
  },
  {
    id: '5',
    make: 'Hyundai',
    model: 'Elantra',
    year: 2019,
    priceUSD: 16000,
    mileage: 55000,
    bodyType: 'Sedán',
    exteriorColor: 'Blue',
    interiorColor: 'Beige',
    transmission: 'Automatic',
    engine: '2.0L 4-Cylinder',
    location: { city: 'Barquisimeto', state: 'Lara', lat: 10.0678, lon: -69.3572 },
    features: ['Cámara de Reversa', 'Bluetooth', 'Control de Crucero'],
    description: 'Moderno y eficiente Hyundai Elantra. Ideal para el uso diario. Espacioso y cómodo, con bajo consumo de combustible.',
    images: [
      getImage('elantra-main'),
    ],
    seller: sellers.seller2,
  },
  {
    id: '6',
    make: 'Kawasaki',
    model: 'Ninja 400',
    year: 2023,
    priceUSD: 8000,
    mileage: 1000,
    bodyType: 'Moto',
    exteriorColor: 'Verde',
    interiorColor: 'Negro',
    transmission: 'Manual',
    engine: '399cc',
    location: { city: 'Caracas', state: 'Distrito Capital', lat: 10.4806, lon: -66.9036 },
    features: ['ABS'],
    description: 'Motocicleta deportiva casi nueva, perfecta para la ciudad y carretera.',
    images: [
      getImage('motorcycle-new'),
    ],
    seller: sellers.seller1,
  },
];
