// Fallback makes and models data, used when Firestore fetch fails
// Extracted to separate file for better tree-shaking and code splitting

import type { MakesByType } from '@/context/makes-context';

export const fallbackData: MakesByType = {
    Carro: {
        Toyota: ['Corolla', 'Hilux', 'Land Cruiser', 'Machito', 'Autana', 'Roraima', 'Merú', 'Prado', '4Runner', 'Fortuner', 'Yaris', 'Belta', 'Camry', 'Tercel', 'Starlet', 'Sky', 'Baby Camry', 'Sapito', 'Pantallita', 'Araya', 'Celica', 'Supra', 'Previa', 'FJ Cruiser', 'Dyna', 'Coaster', 'Etios', 'Raize', 'Corolla Cross', 'Stout'],
        Chevrolet: ['Aveo', 'Optra', 'Spark', 'Cruze', 'Corsa', 'Chevy', 'Astra', 'Cavalier', 'Celebrity', 'Malibu', 'Caprice', 'Silverado', 'Cheyenne', 'Grand Blazer', 'Tahoe', 'Suburban', 'Trailblazer', 'Blazer', 'Luv D-Max', 'Grand Vitara', 'Jimny', 'Vitara', 'Swift', 'Esteem', 'Captiva', 'Onix', 'Groove', 'Montana', 'Colorado', 'Orlando', 'Epica', 'Zafira', 'Kodiak', 'N200', 'N300', 'C3500', 'C10', 'C30', 'S10'],
        Ford: ['Fiesta', 'EcoSport', 'Explorer', 'F-150', 'Fortaleza', 'Triton', 'F-350', 'Super Duty', 'Mustang', 'Focus', 'Laser', 'Festiva', 'Ka', 'Fusion', 'Escape', 'Ranger', 'Bronco', 'Sierra', 'Del Rey', 'Corcel', 'Fairlane', 'Zephyr', 'Conquistador', 'Maverick', 'Falcon', 'F-100', 'Territory', 'Edge', 'Expedition'],
        Mitsubishi: ['Lancer', 'Montero', 'Dakar', 'Sport', 'Montero Limited', 'Signo', 'MF', 'MS', 'MX', 'Galant', 'Eclipse', 'Outlander', 'ASX', 'L200', 'Sportero', 'Panel L300', 'Canter', 'Mirage', 'Space Wagon', 'Expo'],
        Hyundai: ['Accent', 'Getz', 'Elantra', 'Tucson', 'Santa Fe', 'Matrix', 'Atos', 'Excel', 'Sonata', 'Stellar', 'Pony', 'Tiburon', 'Genesis', 'H1', 'H100', 'Starex', 'Creta', 'Grand i10', 'Venue', 'Azera', 'Kona', 'Palisade'],
        Kia: ['Rio', 'Picanto', 'Sportage', 'Sorento', 'Cerato', 'Pregio', 'Carnival', 'Carens', 'K2700', 'Besta', 'Sephia', 'Spectra', 'Mohave', 'Stinger', 'Sonet', 'Seltos', 'Soluto', 'K5'],
        Honda: ['Civic', 'Accord', 'CR-V', 'Fit', 'City', 'HR-V', 'Pilot', 'Odyssey', 'Ridgeline', 'Legend', 'Prelude', 'Integra', 'Stream'],
        Nissan: ['Sentra', 'Tiida', 'Frontier', 'Pathfinder', 'Patrol', 'X-Terra', 'X-Trail', 'Murano', 'Almera', 'B13', 'AD Wagon', '350Z', '370Z', 'Altima', 'Maxima', 'Qashqai', 'Versa', 'Kicks', 'Navara', 'Urvan'],
        Jeep: ['CJ-5', 'CJ-7', 'Wrangler', 'Cherokee', 'Grand Cherokee', 'Wagoneer', 'Gladiator', 'Comanche', 'Renegade', 'Compass', 'Liberty', 'Commander', 'Patriot'],
        Fiat: ['Uno', 'Palio', 'Siena', 'Strada', 'Fiorino', '147', 'Premio', 'Ritmo', 'Regatta', 'Tempra', 'Marea', 'Idea', 'Punto', 'Stilo', 'Mobi', 'Cronos', 'Pulse', 'Fastback', 'Argos', 'Ducato', 'Spazio', 'Tucan'],
        Renault: ['Twingo', 'Clio', 'Logan', 'Sandero', 'Stepway', 'Megane', 'Scenic', 'Laguna', 'Kangoo', 'Duster', 'Oroch', 'Koleos', 'Fluence', 'Symbol', 'R19', 'R21', 'R18', 'R11', 'R12', 'R5', 'Fuego', 'Kwid'],
        Volkswagen: ['Beetle', 'Escarabajo', 'Gol', 'Fox', 'SpaceFox', 'CrossFox', 'Golf', 'Jetta', 'Bora', 'Passat', 'Amarok', 'Tiguan', 'Polo', 'Virtus', 'Nivus', 'Taos', 'T-Cross', 'Parati', 'Saveiro', 'Kombi', 'Transporter', 'Vento', 'Santana'],
        Mazda: ['3', '6', 'Allegro', '626', '323', 'BT-50', 'B2000', 'B2200', 'B2600', 'MX-5', 'Miata', 'CX-5', 'CX-7', 'CX-9', 'CX-30', 'CX-60', 'Demio', 'MPV'],
        Suzuki: ['Swift', 'Jimny', 'Vitara', 'Grand Vitara', 'Baleno', 'Samurai', 'Carry', 'Alto', 'Forsa', 'Sidekick', 'Ignis', 'Ciaz', 'S-Cross', 'Ertiga'],
        Subaru: ['Impreza', 'WRX', 'Forester', 'Outback', 'Legacy', 'XV', 'Crosstrek', 'Vivio', 'Loyale'],
        Peugeot: ['206', '207', '208', '307', '308', '405', '406', '407', '408', '508', '2008', '3008', '5008', 'Partner', 'Expert'],
        Isuzu: ['Trooper', 'LUV', 'Rodeo', 'Amigo', 'Pickup', 'NPR', 'NKR', 'NHR', 'FVR', 'FTR', 'D-Max'],
        Daewoo: ['Lanos', 'Nubira', 'Leganza', 'Cielo', 'Matiz', 'Tico', 'Damas', 'Labo', 'Tacuma', 'Espero', 'Racer'],
        Chery: ['Arauca', 'Orinoco', 'Tiggo', 'Tiggo 2', 'Tiggo 3', 'Tiggo 4', 'Tiggo 7', 'Tiggo 8', 'QQ', 'Cowin', 'Grand Tiger', 'H5'],
        Changan: ['Alsvin', 'Hunter', 'CS15', 'CS35', 'CS55', 'CS75', 'CS85', 'CS95', 'Uni-T', 'Uni-K', 'Benni', 'Star', 'M90'],
        JAC: ['Arena', 'S2', 'S3', 'S5', 'T6', 'T8', 'T9', 'Sunray', 'HFC 1040', 'HFC 1042', 'J2', 'J3', 'J4'],
        Dongfeng: ['S50', 'SX5', 'SX6', 'T5L', 'Rich 6', 'Captain', 'Duolika', 'Aeolus', 'Nano Box'],
        GreatWall: ['Wingle 5', 'Wingle 7', 'Poer', 'Haval H3', 'Haval H5', 'Haval H6', 'Haval Jolion', 'Deer', 'Safe'],
        Baic: ['X25', 'X35', 'X55', 'BJ40', 'BJ80', 'D20'],
        Geely: ['Coolray', 'Azkarra', 'Emgrand', 'GX3', 'Okavango', 'CK', 'MK'],
        Venirauto: ['Turpial', 'Centauro'],
        Saipa: ['Saina', 'Quik', 'Tiba'],
        Ikco: ['Tara', 'Dena', 'Soren', 'Samand'],
        Jetour: ['X70', 'X70 Plus', 'X90 Plus', 'Dashing'],
        Foton: ['Tunland', 'View', 'Ollin', 'Aumark', 'Gratour'],
        MG: ['ZS', 'HS', 'GT', 'MG3', 'MG5', 'MG6', 'RX5', 'RX8'],
        BYD: ['F3', 'F0', 'Yuan', 'Yuan Plus', 'Tang', 'Han', 'Song', 'Dolphin', 'Seal'],
        BMW: ['Serie 1', 'Serie 3', 'Serie 5', 'Serie 7', 'X1', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z3', 'Z4', 'M3', 'M5', 'i3', 'iX'],
        MercedesBenz: ['Clase A', 'Clase B', 'Clase C', 'Clase E', 'Clase S', 'Clase G', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'ML', 'Sprinter', 'Vito', 'SLK', 'CLK'],
        Audi: ['A1', 'A3', 'A4', 'A5', 'A6', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'TT', 'R8', 'E-Tron'],
        Porsche: ['911', 'Cayenne', 'Macan', 'Panamera', 'Taycan', 'Boxster', 'Cayman'],
        LandRover: ['Range Rover', 'Range Rover Sport', 'Range Rover Evoque', 'Velar', 'Discovery', 'Defender', 'Freelander'],
        Volvo: ['S40', 'S60', 'S80', 'S90', 'XC40', 'XC60', 'XC90', 'V40', 'C30'],
        Mini: ['Cooper', 'Countryman', 'Clubman', 'Paceman'],
        Seat: ['Ibiza', 'Leon', 'Cordoba', 'Toledo', 'Altea', 'Inca'],
        Skoda: ['Octavia', 'Fabia', 'Felicia', 'Superb'],
        Citroen: ['C3', 'C4', 'C5', 'Berlingo', 'Jumper', 'Xantia', 'Xsara', 'ZX'],
        Dodge: ['Ram', 'Dakota', 'Durango', 'Dart', 'Neon', 'Caliber', 'Journey', 'Coronet', 'Aspen', 'Spirit'],
        Chrysler: ['Neon', 'Stratus', 'LeBaron', 'Sebring', '300C', 'Town & Country', 'Voyager', 'New Yorker'],
        GAC: ['GS3', 'GS4', 'GS8', 'GA4', 'GN8', 'Emkoo'],
        Maxus: ['T60', 'T90', 'G10', 'V80', 'D60'],
        Kaiyi: ['X3', 'X3 Pro', 'X7'],
        Bestune: ['T33', 'T77', 'T99', 'B70'],
        Riddara: ['RD6'],
        Zotye: ['Nomada', 'Hunter', 'Z100'],
        Lada: ['Niva', 'Samara', '2105', '2107', 'Priora', 'Kalina'],
    },
    Camioneta: {
        Mack: ['Granite', 'Vision', 'CH613', 'R600 (Trompa de Batea)', 'Pinnacle', 'RD690', 'CXU613'],
        Iveco: ['Stralis', 'Trakker', 'EuroCargo', 'Daily (Chasis)', 'EuroTech', 'Cavallino', 'Cursor'],
        Ford: ['Cargo 815', 'Cargo 1721', 'Cargo 2632', 'Cargo 4432', 'F-350', 'F-750', 'F-8000', 'Trader'],
        Chevrolet: ['NPR', 'NQR', 'NKR', 'FVR', 'FSR', 'Kodiak', 'C-70', 'C-3500', 'EXZ (Chuto)'], // En Venezuela los Isuzu se comercializaron bajo Chevrolet
        International: ['WorkStar 7600', 'ProStar', '4300', '4400', '9200', '9400', 'PayStar'],
        Sinotruk: ['Howo 371', 'Howo A7', 'Howo T7H', 'Howo 336'],
        Shacman: ['F3000', 'X3000', 'X2000', 'L3000'],
        Foton: ['Auman', 'Aumark', 'Ollin'],
        JAC: ['Gallop', 'Junbell', 'K5', '1040', '1061', '1131'],
        Dongfeng: ['Kinland', 'Captain', 'Duolika', 'DFL'],
        MercedesBenz: ['Actros', 'Atego', 'Axor', 'L-1620', 'L-1938', 'Accelo', 'Sprinter (Chasis)'],
        Scania: ['113H', '124G', 'G410', 'R420', 'R460', 'P360', 'G380'],
        Volvo: ['FH12', 'FH16', 'FM12', 'FM13', 'VM 270', 'VM 330', 'FMX 440', 'NH12', 'NL10', 'NL12', 'VNL'],
        Freightliner: ['Columbia', 'Cascadia', 'M2 106', 'Century Class', 'FLD 120', 'Argosy'],
        Kenworth: ['T800', 'W900', 'T660', 'T680', 'T2000'],
        Hino: ['Dutro', 'Serie 300', 'Serie 500', 'Serie 700'],
        Volkswagen: ['Constellation', 'Worker', 'Delivery'],
        Kamaz: ['6520', '43253', '65115', '5460'],
        Pegaso: ['1083', '3046', 'Troner'],
    },
    Moto: {
        Bera: ['SBR 150', 'BR-150', 'Corvette', 'Kavak', 'Bera Socialista', 'Runner 150', 'DT 200', 'BR-200', 'Merú', 'Cobra', 'GT 250', 'Milán', 'Bws'],
        EmpireKeeway: ['Horse', 'Horse II', 'Owen', 'Arsen II', 'TX 200', 'Superlight', 'RKV', 'EK Express', 'Matrix', 'Speed 200'],
        Toro: ['Leon 150', 'TR 200', 'Jaguar 150', 'Pantera', 'Rex'],
        MD: ['Haojin', 'Trepador', 'Lechuza', 'Aguila', 'Gavilán', 'Condor', 'Cardenal', 'Tornado'],
        Escuda: ['Scuda 150', 'Scuda 200', 'SBR Escuda'],
        Suzuki: ['GN 125', 'EN 125', 'V-Strom 650', 'V-Strom 1000', 'DR 650', 'GSX-R600', 'DR 200', 'RM-Z'],
        Yamaha: ['DT 175', 'XT 660', 'Ténéré', 'YBR 125', 'FZ16', 'MT-07', 'MT-09', 'R6', 'V-Star', 'YZ 250', 'Jog'],
        Honda: ['CBR 600', 'XR 150L', 'XR 250 Tornado', 'Falcon 400', 'Africa Twin', 'CB 125', 'Wave 110', 'CRF 250', 'Navi'],
        Kawasaki: ['KLR 650', 'Ninja 300', 'Ninja 400', 'Versys 650', 'Z1000', 'KX 250'],
        BMW: ['R 1200 GS', 'R 1250 GS', 'F 800 GS', 'G 310 GS', 'S 1000 RR', 'F 700 GS'],
        KTM: ['Duke 200', 'Duke 390', 'Adventure 390', 'RC 390', 'EXC 300'],
        Benelli: ['TRK 502', 'Leoncino 500', 'TNT 300', 'TNT 600', '302S'],
        Voge: ['300DS', '500DS', '650DS', '300AC'],
        Skygo: ['SG 150', 'SG 200', 'Executive'],
        UM: ['Renegade', 'Max 150', 'DSG 200', 'DSR 200', 'XTreet'],
        Haojue: ['KA 150', 'HJ 150', 'Cool', 'Lucky'],
        AVA: ['Leopard 150', 'Pantera 150', 'Tigre 200'],
        TVS: ['Apache RTR 160', 'Apache RTR 200', 'Ntorq 125'],
        QJMotor: ['SRT 550', 'SRT 800', 'SRK 400'],
        Kayo: ['T2 250', 'T4 250', 'K6 250'],
        Vespa: ['Primavera', 'Sprint', 'GTS 300', 'PX 150'],
        Ducati: ['Monster', 'Multistrada', 'Panigale', 'Scrambler'],
        Loncin: ['Hm 150', 'Gtl 150', 'Ms 250', 'Hm 250ms', 'Nk 250', 'Hm 150 F'],
        Lifan: ['Kpf 150', 'Kpv 350', 'Jojo 125', 'Kps 200'],
    },
};
